# CMake generated Testfile for 
# Source directory: /home/samwise/weinmueller/gismo/examples
# Build directory: /samwise/home/weinmueller/gismo/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(adaptRefinementThb_example "/samwise/home/weinmueller/gismo/bin/adaptRefinementThb_example")
set_tests_properties(adaptRefinementThb_example PROPERTIES  LABELS "examples")
add_test(adaptiveConvectionDiffusionReaction_example "/samwise/home/weinmueller/gismo/bin/adaptiveConvectionDiffusionReaction_example")
set_tests_properties(adaptiveConvectionDiffusionReaction_example PROPERTIES  LABELS "examples")
add_test(assembly_example "/samwise/home/weinmueller/gismo/bin/assembly_example")
set_tests_properties(assembly_example PROPERTIES  LABELS "examples")
add_test(bSplineBasis_example "/samwise/home/weinmueller/gismo/bin/bSplineBasis_example")
set_tests_properties(bSplineBasis_example PROPERTIES  LABELS "examples")
add_test(bSplineCurve_example "/samwise/home/weinmueller/gismo/bin/bSplineCurve_example")
set_tests_properties(bSplineCurve_example PROPERTIES  LABELS "examples")
add_test(bSplineSurface_example "/samwise/home/weinmueller/gismo/bin/bSplineSurface_example")
set_tests_properties(bSplineSurface_example PROPERTIES  LABELS "examples")
add_test(basis_example "/samwise/home/weinmueller/gismo/bin/basis_example")
set_tests_properties(basis_example PROPERTIES  LABELS "examples")
add_test(biharmonic_example "/samwise/home/weinmueller/gismo/bin/biharmonic_example")
set_tests_properties(biharmonic_example PROPERTIES  LABELS "examples")
add_test(commandLineArg_example "/samwise/home/weinmueller/gismo/bin/commandLineArg_example")
set_tests_properties(commandLineArg_example PROPERTIES  LABELS "examples")
add_test(fileIo_example "/samwise/home/weinmueller/gismo/bin/fileIo_example")
set_tests_properties(fileIo_example PROPERTIES  LABELS "examples")
add_test(fitting_example "/samwise/home/weinmueller/gismo/bin/fitting_example")
set_tests_properties(fitting_example PROPERTIES  LABELS "examples")
add_test(geometry_example "/samwise/home/weinmueller/gismo/bin/geometry_example")
set_tests_properties(geometry_example PROPERTIES  LABELS "examples")
add_test(gsInterpolateMap "/samwise/home/weinmueller/gismo/bin/gsInterpolateMap")
set_tests_properties(gsInterpolateMap PROPERTIES  LABELS "examples")
add_test(gsPatchFromBoundary "/samwise/home/weinmueller/gismo/bin/gsPatchFromBoundary")
set_tests_properties(gsPatchFromBoundary PROPERTIES  LABELS "examples")
add_test(gsView "/samwise/home/weinmueller/gismo/bin/gsView")
set_tests_properties(gsView PROPERTIES  LABELS "examples")
add_test(heatEquation_example "/samwise/home/weinmueller/gismo/bin/heatEquation_example")
set_tests_properties(heatEquation_example PROPERTIES  LABELS "examples")
add_test(inputOutput_example "/samwise/home/weinmueller/gismo/bin/inputOutput_example")
set_tests_properties(inputOutput_example PROPERTIES  LABELS "examples")
add_test(knotVector_example "/samwise/home/weinmueller/gismo/bin/knotVector_example")
set_tests_properties(knotVector_example PROPERTIES  LABELS "examples")
add_test(linearAlgebra_example "/samwise/home/weinmueller/gismo/bin/linearAlgebra_example")
set_tests_properties(linearAlgebra_example PROPERTIES  LABELS "examples")
add_test(linearSolvers_example "/samwise/home/weinmueller/gismo/bin/linearSolvers_example")
set_tests_properties(linearSolvers_example PROPERTIES  LABELS "examples")
add_test(mpi_example "/samwise/home/weinmueller/gismo/bin/mpi_example")
set_tests_properties(mpi_example PROPERTIES  LABELS "examples")
add_test(multiGrid_example "/samwise/home/weinmueller/gismo/bin/multiGrid_example")
set_tests_properties(multiGrid_example PROPERTIES  LABELS "examples")
add_test(parametrization_example "/samwise/home/weinmueller/gismo/bin/parametrization_example")
set_tests_properties(parametrization_example PROPERTIES  LABELS "examples")
add_test(poisson2_example "/samwise/home/weinmueller/gismo/bin/poisson2_example")
set_tests_properties(poisson2_example PROPERTIES  LABELS "examples")
add_test(poissonTHB_example "/samwise/home/weinmueller/gismo/bin/poissonTHB_example")
set_tests_properties(poissonTHB_example PROPERTIES  LABELS "examples")
add_test(poisson_example "/samwise/home/weinmueller/gismo/bin/poisson_example")
set_tests_properties(poisson_example PROPERTIES  LABELS "examples")
add_test(sparseSolvers_example "/samwise/home/weinmueller/gismo/bin/sparseSolvers_example")
set_tests_properties(sparseSolvers_example PROPERTIES  LABELS "examples")
add_test(thbRefinement_example "/samwise/home/weinmueller/gismo/bin/thbRefinement_example")
set_tests_properties(thbRefinement_example PROPERTIES  LABELS "examples")
add_test(thbSplineBasis_example "/samwise/home/weinmueller/gismo/bin/thbSplineBasis_example")
set_tests_properties(thbSplineBasis_example PROPERTIES  LABELS "examples")
add_test(triangulatedMeshToSolid_example "/samwise/home/weinmueller/gismo/bin/triangulatedMeshToSolid_example")
set_tests_properties(triangulatedMeshToSolid_example PROPERTIES  LABELS "examples")
add_test(trilinos_example "/samwise/home/weinmueller/gismo/bin/trilinos_example")
set_tests_properties(trilinos_example PROPERTIES  LABELS "examples")
